app:
  name: springboot-jwt-demo

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: queenvictoria
#spring:
#  jpa:
#    hibernate:
#      # possible values: validate | update | create | create-drop
#      ddl-auto: none
#  datasource:
#    url: jdbc:mysql://sql12.freemysqlhosting.net/sql12319617
#    username: sql12319617
#    password: VzV7Hw5Xq6
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  mail:
#    host: smtp.mailtrap.io
#    port: 587
#    username: 18abb0565bf748
#    password: f79f94b6952b50
#    protocol: smtp
#    tls: true
#    properties.mail.smtp:
#      auth: true
#      starttls.enable: true
#      ssl.trust: smtp.mailtrap.io

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thanhdattour?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate.ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialec
    generate-ddl: false
    show-sql: true

#url: jdbc:mysql://localhost/student-manager?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
